services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:${MENDER_CLIENT_TAG}
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
        environment:
            SERVER_URL:
            TENANT_TOKEN:


networks:
    mender:
