services:

    mender-client:
        # Needs to be built in extra/mender-client-docker-addons
        image: mendersoftware/mender-client-docker-addons:${MENDER_CLIENT_TAG}
        networks:
            - mender

networks:
    mender:
