services:
  #
  # monitor-client
  #
  mender-client:
    image: registry.mender.io/mendersoftware/mender-monitor-qemu-commercial:${MENDER_CLIENT_TAG}
    networks:
      - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - SERVER_URL=$SERVER_URL
      - TENANT_TOKEN=$TENANT_TOKEN
networks:
  mender: {}
